MovieShop/MovieShopMVC/Models/ErrorViewModel.cs
using System;

namespace MovieShopMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShop/MovieShopMVC/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService _userService;

        public AccountController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterRequestModel requestModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var newUser = await _userService.RegisterUser(requestModel);
            return View("Login");
            //return to login page
        }
        [HttpGet]
        public IActionResult Register()
        {

            return View();
        }
        //login method should vaidate eamil/password
        //put useauthentication middleware
        //inject cookie name,expiration time in configure service
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginRequestModel requestModel)
        {
            var user = await _userService.LoginUser(requestModel);
            if(user == null)
            {
                // username/password is wrong
                //show message it is wrong
                return View();
            }
            //create cookie
            //tell ASP.NET we will use cookie based authentication
            //claims: exp, username, pwd
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Email,user.Email),
                new Claim(ClaimTypes.GivenName,user.FirstName),
                new Claim(ClaimTypes.NameIdentifier,Convert.ToString(user.Id)),
                new Claim(ClaimTypes.DateOfBirth,user.DateOfBirth.ToShortDateString()),
                new Claim("FullName",user.FirstName+" "+user.LastName)

            };
            //Identity
            //creating the cookie
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
            return LocalRedirect("~/");
            
            //return to login page
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }

    }
}

MovieShop/MovieShopMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieShopMVC.Models;

namespace MovieShopMVC.Controllers
{
    public class HomeController : Controller
    {
        //MovieService service = new MovieService();
        private IMovieService _movieService;
        public HomeController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            
            //call movieservice class to get list of movie cards
            //MovieService _movieService = new MovieService();

            var movieCards = await _movieService.GetTop30RevenueMovies();
            //passing data from controller to view
            return View(movieCards);
        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View("Details");
        }

        [HttpGet]
        public IActionResult TopMovies()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShop/MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var movieDetails = await _movieService.GetMovieDetails(id);

            return View(movieDetails);
        }
    }
}

MovieShop/MovieShopMVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    public class UserController : Controller
    {
        private readonly ICurrentUserService _currentUserService;
        private readonly IUserService _userService;

        public UserController(ICurrentUserService currentUserService, IUserService userService)
        {
            _currentUserService = currentUserService;
            _userService = userService;
        }

        //all for when after authentification
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Purchase(int id)
        {
            var userId = _currentUserService.UserId;
            PurchaseRequestModel request = new PurchaseRequestModel { MovieId = id };
            await _userService.PurchaseMovie(request, userId);
            //var movieId = User.
            //if (userIdentity != null && userIdentity.IsAuthenticated)
            //{
            //    return View();
            //}
            //RedirectToAction("Login", "Account");
            return Content("<script>alert('Purchased Successfully');</script>");
        }


        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Purchases()
        {
            //get all movies purchased by a user
            var userId = _currentUserService.UserId;
            var purchases = await _userService.GetAllPurchasesForUser(userId);
            return View(purchases);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Favorite()
        {
            return View();
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Favorites(int id)
        {
            //get all movies liked by a user
            var userId = _currentUserService.UserId;
            var favorites = await _userService.GetAllFavoritesForUser(userId);
            return View(favorites);
        }

        [HttpPost]
        public async Task<IActionResult> Reviews(ReviewRequestModel reviewRequest,int movieId)
        {
            reviewRequest.UserId = _currentUserService.UserId;
            reviewRequest.MovieId = movieId;
            await _userService.AddMovieReview(reviewRequest);
            return Content("<script>alert('Thanks For Your Comment');</script>");
        }

        [HttpGet]
        public async Task<IActionResult> Reviews(int id)
        {
            return View("review");
        }
    }
}

MovieShop/MovieShopMVC/Views/Home/Index.cshtml
@model List<ApplicationCore.Models.MovieCardResponseModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach (var movieCard in Model)
            {
                <div class="col-xl-2 col-sm-4 col-lg-3 col-6">
                  <partial name="_MovieCard" model="movieCard"/>
                </div>
            }
        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/Home/TopMovies.cshtml
@{
    ViewData["Title"] = "TopMovies";
}

<h1>TopMovies Page</h1>

@if (true)
{
    <p1>Inside an if block.</p1>
}
else
{
    <p2>Inside an else block</p2>
}

MovieShop/MovieShopMVC/Views/Movies/Details-.cshtml
@model ApplicationCore.Models.MovieDetailsResponseModel
@*@{
    ViewData["Title"] = "Details";
}*@

<h1>Details</h1>

<div class="container">
    
    <div class="row">
        <div class="col-sm-4">
            <img src="@Model.PosterUrl" />
        </div>
        <div class="col-sm-4">
            <p>title</p>
            <p>genres</p>
            <p>Rating: @Model.Rating</p>
        </div>
        <div class="col-sm-4">
            <button value="Buy Movie"></button>
            <button value="Review"></button>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            Movie Facts
            <ul class="list-group">
                <li class="list-group-item">Release Date</li>
                <li class="list-group-item">Run Time</li>
                <li class="list-group-item">Box Office</li>
                <li class="list-group-item">Budget</li>
            </ul>
            Trailers
            <ul class="list-group">
                <li class="list-group-item"></li>
            </ul>
            
        </div>
        <div class="col-sm-4">
            Casts
        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsResponseModel
@*@model ApplicationCore.Models.PurchaseRequestModel*@
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">

<div class="container-fluid">
    <div class="bg-image" style="background-image: url(@Model.BackdropUrl)">

        <div class="row">
            <div class="col-md-3 offset-2">

                <!-- Movie Card row -->
                <div>
                    <img src="@Model.PosterUrl" class="card-img-top img-fluid" />
                </div>

            </div>
            <div class="col-md-4">
                <div class="row mt-2">
                    <div class=".col-md-6 .offset-md-3">
                        <h1 class="text-white">
                            @Model.Title
                        </h1>
                        <small class="text-muted"> @Model.Tagline </small>
                    </div>

                </div>

                <div class="row">
                    <div class="col-4 text-secondary font-weight-bold mt-2">

                        @Model.RunTime m | @Model.ReleaseDate.Value.Date.Year
                    </div>
                    <div class="col-8">

                        @foreach (var genre in Model.Genres)
                        {
                            <a asp-controller="Movies" asp-action="Genre" asp-route-id="@genre.Id" class="badge badge-pill badge-dark ml-1">
                                @genre.Name
                            </a>
                        }
                    </div>
                </div>

                <div class="row">
                    <div class="col-4 mt-3">
                        <h4>
                            <span class="badge badge-warning">
                                @Model.Rating?.ToString("0.00")
                            </span>
                        </h4>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 text-light mt-2">
                        @Model.Overview
                    </div>
                </div>
            </div>

            <div class="col-md-2 mt-4 offset-1">
                <ul class="list-group">
                    <li class="list-group-item-dark">
                        <a class="dropdown-item" asp-controller="User" asp-action="Purchases">
                            Purchases
                        </a>
                    </li>
                    <li class="list-group-item-dark">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                            REVIEW
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Write Your Review Here...</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form asp-controller="user" asp-action="reviews">
                                            <div class="mb-3" style=" display:none">
                                                <input type="text" class="form-control mid" name="movieid" value="@Model.Id">
                                            </div>
                                            <div class="mb-3">
                                                <label for="rating" class="form-label">Rating</label>
                                                <input type="text" class="form-control" name="rating" placeholder="1~5">
                                            </div>
                                            <div class="mb-3">
                                                <label for="reviewtext" class="form-label">Review</label>
                                                <textarea class="form-control" name="reviewtext" rows="3"></textarea>
                                            </div>

                                            <div class="mb-3">
                                                <button type="submit" class="btn btn-primary mb-3">submit</button>
                                            </div>
                                        </form>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>

                    </li>
                    <li class="list-group-item-dark">
                        <form asp-controller="user" asp-action="purchase" asp-route-id="@Model.Id">
                            <input type="submit" value="Buy @Model.Price" class="btn btn-primary" />
                        </form>
                        
                    </li>

                </ul>
                

            </div>
            <div class="dropdown">
                <a class="btn btn-secondary dropdown-toggle" href=" " role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-expanded="false">
                    lkj
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" asp-controller="User" asp-action="Purchases">
                        Purchases
                    </a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Favorites">
                        Favorites
                    </a>
                    <a class="dropdown-item" asp-controller="User" asp-action="">
                        Edit Profile
                    </a>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a>
                </div>
            </div>

        </div>
    </div>


    <div class="row mt-4">
        <div class="col-4 moviefacts">
            <h5>MOVIE FACTS</h5>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <i class="bi bi-calendar-week"></i>Release Date
                    <span class="badge badge-pill badge-dark">@Model.ReleaseDate.Value.ToShortDateString()</span>
                </li>

                <li class="list-group-item">
                    <i class="bi bi-hourglass-split"></i>Run Time
                    <span class="badge badge-pill badge-dark">@Model.RunTime.Value m</span>
                </li>
                <li class="list-group-item">
                    <i class="bi bi-bag-check"></i> Box Office
                    <span class="badge badge-pill badge-pill badge-dark">
                        @Model.Revenue?.ToString("C0")
                    </span>
                </li>

                <li class="list-group-item">
                    <i class="bi bi-currency-dollar"></i> Budget
                    <span class="badge badge-pill badge-dark">
                        @Model.Budget?.ToString("C0")
                    </span>
                </li>


            </ul>
            <h5>TRAILERS</h5>
            <ul class="list-group-flush">
                @foreach (var trailer in Model.Trailers)
                {
                    <li class="list-group-item" style="height:auto">
                        <span>
                            <i class="bi bi-youtube"></i>
                            <a href="@trailer.TrailerUrl">@trailer.Name</a>
                        </span>

                    </li>
                }

            </ul>
        </div>


        <div class="col-7 offset-1">
            <h5>CASTS</h5>
            <ul class="list-group-flush">
                @foreach (var cast in Model.Casts)
                {
                    <li class="list-group-item" style="height:auto">
                        <span>
                            <img src="@cast.ProfilePath"
                                 class="rounded-circle"
                                 style="height:50px" />
                            @cast.Name
                            @cast.Character
                        </span>
                    </li>
                }

            </ul>


        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/Shared/_CastList.cshtml
@model ApplicationCore.Models.MovieCardResponseModel

<div class="card mb-4">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>

MovieShop/MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name ="_LoginInfoPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MovieShop/MovieShopMVC/Views/Shared/_LoginInfoPartial.cshtml
@using MovieShopMVC.Services
@inject ICurrentUserService _currentUserService

@if (_currentUserService.IsAuthenticated)
{
    /*First Name Last Name, Edit Profile, Logout */
    <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href=" " role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-expanded="false">
            @_currentUserService.FullName
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" asp-controller="User" asp-action="Purchases">
                    Purchases</a>
                    <a class="dropdown-item" asp-controller="User" asp-action="Favorites">
                        Favorites</a>
                        <a class="dropdown-item" asp-controller="User" asp-action="">
                            Edit Profile</a>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a>
            </div>
    </div>
}
else
{
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a asp-controller="Account" asp-action="Login" class="btn btn-outline-primary"> Login</a>
            </li>
            <li class="nav-item">
                <a asp-controller="Account" asp-action="Register" class="btn btn-outline-primary"> Register</a>
            </li>
        </ul>
    </div>
}

MovieShop/MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardResponseModel

<div class="card mb-4">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>

MovieShop/MovieShopMVC/Views/Shared/_buy.cshtml
@model ApplicationCore.Models.PurchaseRequestModel

    <form asp-controller="User" asp-action="Purchase">
        <input type="submit" value="BUY" class="btn btn-primary" asp-for="@Model.MovieId" />
    </form>

MovieShop/MovieShopMVC/Views/User/Favorites.cshtml
@model ApplicationCore.Models.FavoriteResponseModel
@{
    ViewData["Title"] = "Purchases";
}

<h1>Purchase</h1>

<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach (var movieCard in Model.FavoriteMovies)
            {
                <div class="col-xl-2 col-sm-4 col-lg-3 col-6">
                    <partial name="_MovieCard" model="movieCard" />
                </div>
            }
        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/User/Purchases.cshtml
@model ApplicationCore.Models.PurchaseResponseModel
@{
    ViewData["Title"] = "Purchases";
}

<h1>Purchase</h1>

<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach (var movieCard in Model.PurchasedMovies)
            {
                <div class="col-xl-2 col-sm-4 col-lg-3 col-6">
                    <partial name="_MovieCard" model="movieCard" />
                </div>
            }
        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/User/Review.cshtml
@model ApplicationCore.Models.ReviewRequestModel
@{
    ViewData["Title"] = "Review";
}

<h1>Review</h1>
<form asp-action="reviews">
    <div class="mb-3">
        <label for="rating" class="form-label">Rating</label>
        <input type="text" class="form-control" name="rating" placeholder="1~5">
    </div>
    <div class="mb-3">
        <label for="reviewtext" class="form-label">Review</label>
        <textarea class="form-control" name="reviewtext" rows="3"></textarea>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary mb-3">Confirm identity</button>
    </div>
</form>

MovieShop/MovieShopMVC/Views/User/purchase.cshtml
@{
    ViewData["Title"] = "purchase";
}

<h1>purchase</h1>